spring:
    datasource:
       name: dataSource
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: sqltoy
       password: sqltoy
       url: jdbc:mysql://192.168.56.109:3306/sqltoy?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
       druid:
         initial-size: 5
         min-idle: 5
         maxActive: 20
         # 配置获取连接等待超时的时间
         maxWait: 60000
         numTestsPerEvictionRun: 3
         keepAlive: true
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         timeBetweenEvictionRunsMillis: 120000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
         minEvictableIdleTimeMillis: 600000
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: true
         testOnReturn: false
         removeAbandoned: true
         removeAbandonedTimeout: 300
    data:
       mongodb:
           host: 192.168.56.109
           port: 27017
           database: sagframe
           username: sagframe
           password: sagframe
    sqltoy:
        # 多个路径用逗号分隔
        sqlResourcesDir: classpath:com/sagframe/sqltoy/showcase
        # 默认为classpath:sqltoy-translate.xml，一致则可以不用设置
        translateConfig: classpath:sqltoy-translate.xml
        # 默认为false，debug模式将打印执行sql,并自动检测sql文件更新并重新加载
        debug: true
        # 设置默认使用的datasource(可选配置)
        defaultDataSource: dataSource
        # sql执行超过多长时间则进行日志输出,用于监控哪些慢sql(可选配置:默认30秒)
        printSqlTimeoutMillis: 300000
        elastic:
           defaultId: default
           endpoints[0]:
                       id: default
                       url: http://192.168.56.104:9200
                       username: elastic
                       password: SagFrame@123
                       version: 7.5.1